branches:
  only:
    - master
   #except:
    #- master

image:
  - Ubuntu
  - Ubuntu1604
  - Ubuntu2004

environment:
  # secure values
  SKEY:
    secure: YyPit9bsTGKQYJEkmv6qAajHzVj+OV9UQKRL5b/sHyJ2SuzSDmjEZO0JRSLlbdyW
  COVERALLS_REPO_TOKEN:
    secure: tyj1Sii8/fPCjipAJUxxlXO1IhvCXFIyiZE0cPuYKHGGiyKgbUq5O0xD34VUq5E/
  # common values
  SONAR_SCANNER_VERSION: 4.2.0.1873
  SONAR_SCANNER_OPTS: -server
  # default values
  PYTHON: 3.6
  ENABLED: true
  
  WEEWX_URL: http://www.weewx.com/downloads/released_versions/

  matrix:
    - PYTHON: 3.8
      WEEWX: 4.8.0
      CODECOVIO_UPLOAD: true
      COVERALLS_UPLOAD: true
      SONAR_UPLOAD: true
      job_group: build  
      job_depends_on: initialize

    - PYTHON: 2.7
      WEEWX: 4.8.0
      CODECOVIO_UPLOAD: true
      job_group: build  
      job_depends_on: initialize

    - PYTHON: 3.5.10
      WEEWX: 4.8.0
      job_group: build  
      job_depends_on: initialize      

    - PYTHON: 3.6
      WEEWX: 4.8.0
      job_group: build
      job_depends_on: initialize

    - PYTHON: 3.7
      WEEWX: 4.8.0
      job_group: build  
      job_depends_on: initialize

    - PYTHON: 3.9
      WEEWX: 4.8.0
      job_group: build  
      job_depends_on: initialize

    - PYTHON: 2.7
      WEEWX: 3.9.0 
      job_group: build
      job_depends_on: initialize

    - PYTHON: 2.7 
      WEEWX: 3.7.1
      job_group: build
      job_depends_on: initialize

    - PYTHON: 3.8
      WEEWX: master
      job_group: build  
      job_depends_on: initialize      

    - PYTHON: 3.8
      WEEWX: development
      job_group: build  
      job_depends_on: initialize      

    # Build/Test against a development/pre release of WeeWX
    # These do not always exist
    - ENABLED: false
      PYTHON: 3.8
      WEEWX: 4.6.0a4
      WEEWX_URL: http://www.weewx.com/downloads/development_versions/
      job_group: build  
      job_depends_on: initialize

    - job_name: initialize
      WEEWX_URL: http://www.weewx.com/downloads/development_versions/

    - job_name: finalize
      job_depends_on: build
      WEEWX_URL: http://www.weewx.com/downloads/development_versions/

stack: python %PYTHON%      

for:
- 
  matrix:
    only:
    - job_name: initialize

  install:
    - sh: echo "install unneeded"    

  build: off

- 
  matrix:
    only:
    - job_name: finalize

  install:
    - sh: echo "install unneeded"    

  build_script:
    - sh: echo "finalize"
    #- sh: curl -k https://coveralls.io/webhook?repo_token=$COVERALLS_REPO_TOKEN -d "payload[build_num]=$APPVEYOR_BUILD_ID&payload[status]=done"

- 
  matrix:
    only:
    - job_group: build

  build_script:
    - sh: echo "build_script"
    - sh: appveyor/build_script.sh  

  test_script:
    - sh: echo "test_script"
    - sh: appveyor/test_script.sh

  after_test:
    - sh: echo "after_test"
    - sh: appveyor/after_test.sh

# common/default scripts
init:
  # This runs before the commit is even checked out
  - sh: echo "init"
  - sh: echo "$APPVEYOR_BUILD_WORKER_IMAGE"

install:
  - sh: echo "install"
  # 'source' so that variables are set in parent environment
  - sh: source appveyor/init.sh 
  - sh: appveyor/install.sh    
   
on_finish:
  - sh: echo "on_finish"
  - sh: appveyor/on_finish.sh
