# control which branches use this file
branches:
  #only:
    #- master
  except:
    - master

# Environment variables with names that match build image can be a list of broken python versions.
# For example Ubuntu1604="3.10 3.11"
# These are typically set in the appveyor ui, environment tab.
# This makes it easy to modify and rebuild.
# This is used in the 'init script' below
# To allow easily checking/updating broken images, these are set in the GUI.

# branch build uses a subset of appveyor images, master uses all
image:
  - Ubuntu
  #- Ubuntu2004
  #- Ubuntu2204

# everything below this line should be identical when comparing branch build to master build

# Do not build on tags (GitHub, Bitbucket, GitLab, Gitea)
# skip_tags: true

# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true

environment:
  # secure values
  SKEY:
    secure: YyPit9bsTGKQYJEkmv6qAajHzVj+OV9UQKRL5b/sHyJ2SuzSDmjEZO0JRSLlbdyW
  COVERALLS_REPO_TOKEN:
    secure: tyj1Sii8/fPCjipAJUxxlXO1IhvCXFIyiZE0cPuYKHGGiyKgbUq5O0xD34VUq5E/
  # common values
  SONAR_SCANNER_VERSION: 4.2.0.1873
  SONAR_SCANNER_OPTS: -server
  # default values
  # default to oldest supported version of python
  PYTHON_LATEST: 3.11
  PYTHON: 3.7
  ENABLED: true
  
  WEEWX_URL: http://www.weewx.com/downloads/released_versions/

  matrix:
    # Run tests against latest WeeWX and Python
    # This run uploads test results and sonar results
    # Run first, so that completes early
    - PYTHON: %PYTHON_LATEST%
      WEEWX: 4.10.2
      CODECOVIO_UPLOAD: true
      COVERALLS_UPLOAD: true
      SONAR_UPLOAD: true
      job_group: build  
      job_depends_on: initialize

    # Start of runs against latest WeeWX release and supported versions of Python
    # Even though EOL, I'll support a bit longer

    - PYTHON: 3.7
      WEEWX: 4.10.2
      job_group: build  
      job_depends_on: initialize

    - PYTHON: 3.8
      WEEWX: 4.10.2
      job_group: build  
      job_depends_on: initialize

    - PYTHON: 3.9
      WEEWX: 4.10.2
      job_group: build  
      job_depends_on: initialize

    - PYTHON: 3.10
      WEEWX: 4.10.2
      job_group: build  
      job_depends_on: initialize

    - PYTHON: 3.11
      WEEWX: 4.10.2
      job_group: build  
      job_depends_on: initialize

    # not yet supported
    #- PYTHON: 3.12
      #WEEWX: 4.10.2
      #job_group: build  
      #job_depends_on: initialize

    # End of runs against latest WeeWX release and supported versions of Python

    # The earliest WeeWX version supported
    - PYTHON: 3.9
      WEEWX: 4.0.0
      job_group: build
      job_depends_on: initialize

    # Use latest Python release against WeeWX master branch
    - PYTHON: 3.9
      BRANCH: master
      WEEWX: '%BRANCH%'
      job_group: build  
      job_depends_on: initialize      

    # Use latest Python release against WeeWX development branch
    - PYTHON: 3.9
      BRANCH: development
      WEEWX: '%BRANCH%'
      job_group: build  
      job_depends_on: initialize      

    # Use latest Python release against WeeWX V5 branch
    - PYTHON: 3.9
      BRANCH: V5
      WEEWX: '%BRANCH%'
      job_group: build  
      job_depends_on: initialize            

    # Build/Test against a development/pre release of WeeWX with latest Python
    # These do not always exist
    - ENABLED: false
      PYTHON: 3.9
      WEEWX: 4.9.0b1
      WEEWX_URL: http://www.weewx.com/downloads/development_versions/
      job_group: build  
      job_depends_on: initialize

    - job_name: initialize
      WEEWX_URL: http://www.weewx.com/downloads/development_versions/

    - job_name: finalize
      job_depends_on: build
      WEEWX_URL: http://www.weewx.com/downloads/development_versions/

stack: python %PYTHON%      

for:
- 
  matrix:
    only:
    - job_name: initialize

  install:
    - sh: echo "install unneeded"    

  build: off

- 
  matrix:
    only:
    - job_name: finalize

  install:
    - sh: echo "install unneeded"    

  build_script:
    - sh: echo "finalize"
    #- sh: curl -k https://coveralls.io/webhook?repo_token=$COVERALLS_REPO_TOKEN -d "payload[build_num]=$APPVEYOR_BUILD_ID&payload[status]=done"

- 
  matrix:
    only:
    - job_group: build

  build_script:
    - sh: echo "build_script"
    - sh: appveyor/build_script.sh  

  test_script:
    - sh: echo "test_script"
    - sh: appveyor/test_script.sh

  after_test:
    - sh: echo "after_test"
    - sh: appveyor/after_test.sh

# common/default scripts
init:
  # This runs before the commit is even checked out
  # Therefore cannot run scripts in Github
  - sh: echo "init"
  - sh: echo "$APPVEYOR_BUILD_WORKER_IMAGE $PYTHON"
  - sh: echo "${!APPVEYOR_BUILD_WORKER_IMAGE}"
  - sh: >-
      if [[ ${!APPVEYOR_BUILD_WORKER_IMAGE} == *$PYTHON* ]]; then
        echo "$APPVEYOR_BUILD_WORKER_IMAGE with $PYTHON is broken on Appveyor."
        exit 0
      fi;

install:
  - sh: echo "install"
  # 'source' so that variables are set in parent environment
  - sh: source appveyor/init.sh   
  - sh: appveyor/install.sh    
   
on_finish:
  - sh: echo "on_finish"
  - sh: appveyor/on_finish.sh
