export SONAR_SCANNER_HOME=$HOME/.sonar/sonar-scanner-$SONAR_SCANNER_VERSION-linux
export PATH=$SONAR_SCANNER_HOME/bin:$PATH

echo $APPVEYOR_REPO_TAG
echo $APPVEYOR_REPO_TAG_NAME

if [ "$APPVEYOR_REPO_TAG" = "true" ]; then
  echo APPVEYOR_BUILD_VERSION=$APPVEYOR_REPO_TAG
  appveyor UpdateBuild -Version "$APPVEYOR_REPO_TAG"
fi