name: Analyze and test

on:
  push:
    branches-ignore: [ "master" ]

jobs:
  analyze-test:
    uses: weewx-extensions/development_tools/.github/workflows/analyze-test.yml@v3
    with:
      module-name: 'MQTTSubscribe'
      pip-list: 'paho-mqtt'
      package-list: 'mosquitto'
      flake-extra-parms: '--exclude tests'
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
